### ISSUE TITLE
Week 4 ready for review

### ISSUE THREAD

**Issue by eferr216** [eferr216/weatherWhere#1]
@pawaitemadisoncollege Week 4 Project portion is now ready for review.

**Comment by pawaitemadisoncollege** [comment]
Hi @eferr216. You have a good start with Hibernate in your indie project! 

- [ ] Here, I wonder if a special method is needed, or if the getByPropertyLike method can accomplish this? https://github.com/eferr216/weatherWhere/blob/16919676c3ad9384ef12c8a71d7a509b708e691c/src/main/java/edu/matc/persistence/ItemDao.java#L43

- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedItem.equals(actualItem));` so that you don't have to compare each instance var/column manually like this: https://github.com/eferr216/weatherWhere/blob/16919676c3ad9384ef12c8a71d7a509b708e691c/src/test/java/edu/matc/persistence/ItemDaoTest.java#L84

- [ ] It looks like there might be something off in the log4j properties file that is creating this directory. I think this might happen if the `filepath` variable doesn't exist.
![filepath](https://github.com/eferr216/weatherWhere/assets/13874466/d6bbb152-a781-4eab-9815-60daaac4e765)
